CREATE DATABASE cadastro;

USE cadastro;

CREATE TABLE usuarios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tipo_cadastro VARCHAR(10) NOT NULL,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE administradores (
  id INT PRIMARY KEY AUTO_INCREMENT,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE usuarios_comuns (
  id INT PRIMARY KEY AUTO_INCREMENT,
  usuario VARCHAR(50) NOT NULL,
  senha VARCHAR(255) NOT NULL
);